// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRegisterApi.Data;

#nullable disable

namespace StudentRegisterApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231222151754_seeed data")]
    partial class seeeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentRegisterApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studnts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "colombo",
                            Name = "chathura",
                            Phone = "0774733245"
                        },
                        new
                        {
                            Id = 2,
                            Address = "kandy",
                            Name = "Kamal",
                            Phone = "0786543213"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Galle",
                            Name = "Amara",
                            Phone = "0775645890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
